# Generated by Django 3.2.18 on 2023-04-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag_options',
            field=models.ManyToManyField(to='tags.Option'),
        ),
        migrations.DeleteModel(
            name='TagOption',
        ),
    ]
