# Generated by Django 3.2.18 on 2023-04-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailauth',
            name='is_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailauth',
            name='type',
            field=models.CharField(choices=[('JOIN', 'JOIN'), ('PASSWORD', 'PASSWORD')], default='JOIN', max_length=12),
        ),
    ]
