# Generated by Django 3.2.18 on 2023-04-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_last_login_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('withdraw', 'withdraw')], default='active', max_length=12),
        ),
    ]
