# Generated by Django 3.2.18 on 2023-04-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=models.FilePathField(null=True),
        ),
    ]
